#!/usr/bin/env sh
#~/.local/bin/bartoggle & #tint2
#~/.config/polybar/minimal/launch.sh       
~/.config/polybar/i3-bar/launch

if [[ $(pidof dunst) ]]; then
   pkill dunst
fi

dunst -config .config/dunst/i3-dunstrc  &&

killall -q picom
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom -f --config ~/.config/picom/picom.conf -b &

