#!/usr/bin/env bash

HELPER(){
	read foo 
	echo $foo | ~/.scripts/notification_helper media
}



case $1 in
	--pp)
		playerctl play-pause
 		echo 'play-pause' | HELPER
		;;
	--stop)
		playerctl stop 
		echo 'Stopped' | HELPER
		;;
	--prev)
		playerctl previous 
		echo 'Now Playing' | HELPER
		;;
	--next)
		playerctl next 
		echo 'Now Playing' | HELPER
		;;
	--shuffle)
        playerctl shuffle toggle
        echo 'shuffle' | HELPER
		;;
    --repeat)
        my_array=(None Track Playlist)
        value="$(playerctl metadata --format '{{loop}}')"
        for i in "${!my_array[@]}"; do
            if [[ "${my_array[$i]}" = "${value}" ]]; then
                loop="${i}";
            fi
        done
        loop=$((loop+1))
        loop=$((loop%3))

        playerctl loop "${my_array[loop]}"
        echo 'repeat' | HELPER
        ;;
esac
