let mapleader=" "

let &t_ut=''

if has('filetype')
	set autoindent
	filetype indent plugin on
endif

"dein Plugin manager-----------------------------
if &compatible
	set nocompatible               " Be iMproved
endif

"End dein ---------------------------------------

if has('syntax')
	syntax on
endif

if has('mouse')
	set mouse=a
endif

if has('clipboard')
	nmap <C-V> "+gP
	imap <C-V> <ESC><C-V>ia
	vmap <C-C> "+y
endif

" Display all matching files when tab-complete
set wildmenu
" - find by partial match
" - * fuzzy search
" - :b autocomplete open buffers

set showcmd
set hlsearch
set ignorecase
set smartcase
set nostartofline
set ruler
set laststatus=2
set confirm
set visualbell
set cmdheight=2
set tabstop=2
set number
"set autochdir

set guicursor+=n-v-c:blinkon0

autocmd InsertEnter,InsertLeave * set cul!

"FINDING FILES
"Search through sub folders
"Tab-completion for file related tasks
set path+=**

" TAG JUMPING
" - requires ctags
" - ^] tag under cursor
" - g^] ambiguous tag
" - ^t back to tag stack
" - Not visual  
command! MakeTags !ctags -R .

"AUTOCOMPLETE
" - ^n for suggestion ^p to traverse suggestion
" - ^x^n only from current file
" - ^x^f for filenames
" - ^x^] for tags only
" - ^n autocomplete from default completion
"

au BufNewFile,BufRead *.py set tabstop=4 softtabstop=4 shiftwidth=4 expandtab smarttab autoindent 

"FILE BOWSING
" - 
"

"SNIPPETS
" noremap ,html : -lread <__FILE__><CR>3jwf>a
" - <CR> carriage return code of vim
"
command FileSyn execute "vnew | r !file_sync # "
command FormatJSON execute "%!json_pp"
command FormatXML execute "%!python -c 'import sys; import xml.dom.minidom; s=sys.stdin.read(); print(xml.dom.minidom.parseString(s).toprettyxml())'"

aug StdIn
  au! 
  au StdinReadPost * echomsg "In pager mode!"
  silent loadview
aug END

function! ToggleEnterMapping()
  if empty(mapcheck('<CR>', 'i'))
    inoremap <CR> <Esc>`^
    return "\<Esc>"
  else
    iunmap <CR>
    return "\<CR>"
  endif
endfunction

call ToggleEnterMapping()
inoremap <expr> <S-CR> ToggleEnterMapping()
" Optional (so <CR> cancels prefix, selection, operator).
nnoremap <CR> <Esc>
vnoremap <CR> <Esc>gV
onoremap <CR> <Esc>


nmap <Leader>\ :vsplit<CR>
nmap <Leader>- :split<CR>

nnoremap <Leader><Leader>r :%s//g<Left><Left>
xnoremap <Leader><Leader>r :s//g<Left><Left>

vnoremap J :m '>+1<CR>
" xnoremap K :m '<-2<CR>
vnoremap K :m '<-2<CR>

" Put search results in the middle of the screen
nnoremap n nzz
nnoremap N Nzz

