let mapleader=" "

let &t_ut=''

if has('filetype')
	set autoindent
	filetype indent plugin on
endif

"dein Plugin manager-----------------------------
if &compatible
	set nocompatible               " Be iMproved
endif

set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim

" Required:
call dein#begin('~/.cache/dein')
	call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')
	source ~/.vim/plugin_conf/_NERDTree.vim
	call dein#add('ludovicchabant/vim-lawrencium')
	call dein#add('tpope/vim-fugitive')
	call dein#add('terryma/vim-multiple-cursors')
	"call dein#add('Shougo/neosnippet.vim')
	""call dein#add('Shougo/neosnippet-snippets')
call dein#end()

" If you want to install not installed plugins on startup.
if dein#check_install()
	call dein#install()
endif

"End dein ---------------------------------------

if has('syntax')
	syntax on
endif

if has('mouse')
	set mouse=a
endif

if has('clipboard')
	nmap <C-V> "+gP
	imap <C-V> <ESC><C-V>ia
	vmap <C-C> "+y
endif

" Display all matching files when tab-complete
set wildmenu
" - find by partial match
" - * fuzzy search
" - :b autocomplete open buffers

set showcmd
set hlsearch
set ignorecase
set smartcase
set nostartofline
set ruler
set laststatus=2
set confirm
set visualbell
set cmdheight=2
set number
"set autochdir

set guicursor+=n-v-c:blinkon0

autocmd InsertEnter,InsertLeave * set cul!

"FINDING FILES
"Search through sub folders
"Tab-completion for file related tasks
set path+=**

" TAG JUMPING
" - requires ctags
" - ^] tag under cursor
" - g^] ambiguous tag
" - ^t back to tag stack
" - Not visual  
command! MakeTags !ctags -R .

"AUTOCOMPLETE
" - ^n for suggestion ^p to traverse suggestion
" - ^x^n only from current file
" - ^x^f for filenames
" - ^x^] for tags only
" - ^n autocomplete from default completion
"

"FILE BOWSING
" - 
"

"SNIPPETS
" noremap ,html : -lread <__FILE__><CR>3jwf>a
" - <CR> carriage return code of vim
"
command FileSyn execute "vnew | r !file_sync # "
command FormatJSON execute "%!json_pp"
command FormatXML execute "%!python -c 'import sys; import xml.dom.minidom; s=sys.stdin.read(); print(xml.dom.minidom.parseString(s).toprettyxml())'"

"BUILD INTEGRATION
"set makeprg= <__COMMAND__>

nmap <F6> :NERDTreeToggle<CR>
