#!/usr/bin/env sh
#~/.local/bin/bartoggle & #tint2
~/.config/polybar/minimal/launch.sh       

command -v hhp >/dev/null 2>&1 && hhp&
command -v conky >/dev/null 2>&1 && sleep 5;~/.config/conky/hax_os/start&
