#!/usr/bin/env bash

_lock-run_revert(){
    $HOME/.local/bin/eww -c ~/.config/eww/Lock/ close-all
}

trap _lock-run_revert HUP INT TERM

notify-send "Locking" 
$HOME/.scripts/lock/i3lock-widgets &&

#pkill -u "$USER" -USR2 dunst
pkill cycle-dim
pkill wait-suspend
kill $(ps -ef | grep ".scripts/lock/cycle-dim" |  grep -v grep  | awk '{print $2}')
_lock-run_revert


#$HOME/.scripts/unlock-bg
