#!/bin/sh
. ~/.scripts/notify/audio --source-only

icon() {
        vol=$(getdefaultsinkvol)

        if [[ ${vol} -ge 75 ]]; then
                echo ""
        elif [[ ${vol} -ge 50 ]]; then
                echo ""
        elif [[ ${vol} -ge 25 ]]; then
                echo ""
        else
                echo ""
        fi
}

if [[ $1 = "-l" ]]; then
        echo $(getdefaultsinkvol)
elif [[ $1 = '-i' ]]; then
        icon
fi
