#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Fullscreen terminal
kitty  --hold --single-instance --detach --wait-for-single-instance-window-close --start-as normal --class "kitty-cava" cava
