$nshell_ipc_call = qs -c noctalia-shell ipc call
bind = $mainMod, p, exec, $nshell_ipc_call launcher toggle
# screenshot stuff
bind = , Print, exec, ~/bin/screenshot.sh screen
bind = $mainMod, Print, exec, ~/bin/screenshot.sh area
bind = Shift, Print, exec, ~/bin/screenshot.sh output
bind = CONTROL, Print, exec, ~/bin/qr.sh

# function keys
bind = , XF86AudioPrev, exec, $nshell_ipc_call media previous
bind = , XF86AudioNext, exec, $nshell_ipc_call media next
bind = , XF86AudioPlay, exec, $nshell_ipc_call media playPause

bind = , XF86AudioLowerVolume, exec,$nshell_ipc_call volume decrease
bind = , XF86AudioRaiseVolume, exec,$nshell_ipc_call volume increase
bind = , XF86AudioMute, exec,  exec,$nshell_ipc_call volume muteOutput

bind = , XF86MonBrightnessDown, exec,$nshell_ipc_call brightness increase
bind = , XF86MonBrightnessUp, exec,$nshell_ipc_call brightness decrease

bind = , XF86Launch1, exec, nautilus -w
bind = , XF86Launch2, exec, zen-browser
bind = Shift, XF86Launch2, exec, zen-browser --private-window

