bind = $mainMod, p, exec, anyrun 

# screenshot stuff
bind = , Print, exec, ~/bin/screenshot.sh screen
bind = $mainMod, Print, exec, ~/bin/screenshot.sh area
bind = Shift, Print, exec, ~/bin/screenshot.sh output
bind = CONTROL, Print, exec, ~/bin/qr.sh

# function keys
bind = , XF86AudioPrev, exec, playerctl previous
bind = , XF86AudioNext, exec, playerctl next
bind = , XF86AudioPlay, exec, playerctl play-pause
bind = , XF86AudioLowerVolume, exec, wpctl set-volume  @DEFAULT_AUDIO_SINK@ 2%- 
bind = , XF86AudioRaiseVolume, exec, wpctl set-volume  @DEFAULT_AUDIO_SINK@ 3%+
bind = , XF86AudioMute, exec, wpctl set-mute  @DEFAULT_AUDIO_SINK@ toggle
bind = , XF86MonBrightnessDown, exec, brightnessctl set 5%-
bind = , XF86MonBrightnessUp, exec, brightnessctl set +5%
bind = , XF86Launch1, exec, nautilus -w
bind = , XF86Launch2, exec, zen-browser
bind = Shift, XF86Launch2, exec, zen-browser --private-window

