(defun c-save-compile ()
  (interactive)
  (save-buffer)
  (shell-command (concat "g++ " (buffer-name) " -g -pg -std=c++0x -o " (buffer-name) ".out" ))
)
(eval-after-load 'cc-mode 
  (lambda ()
    (define-key c++-mode-map (kbd "<f5>") 'c-save-compile)
    (define-key c++-mode-map (kbd "<C-f5>") 
	'(lambda() (interactive)(shell-command (concat "./" (buffer-name) ".out")))
    )
  )
)
(provide 'cc-config)

