#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo $DIR

dir=$DIR/../styles

rofi -theme $dir/launcher.rasi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}'

