#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo $DIR
cmd="~/.local/bin/greenclip "
dir=$DIR/../styles

rofi -theme $dir/launcher.rasi -modi "Clipboard:$cmd print" -show Clipboard -run-command '{cmd}'

