#!/usr/bin/env bash

## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3
# wayland : https://www.reddit.com/r/wayland/comments/fbhiez/color_picker_eyedropper_on_wayland/ 
## Simple Script To Pick Color Quickly.

DispSer=$(loginctl show-session $(loginctl|grep $(whoami) |awk '{print $1}') -p Type | cut -d= -f 2)

if [[ "$DispSer" == "wayland" ]]; then
  #color=$(grim -g "$(slurp -p)" -t ppm - | convert - -format '%[pixel:p{0,0}]' txt:-)
  color="$(grim -g "$(slurp -p)" - -t png -o | convert png:- -format '%[pixel:s]\n' info:- | awk -F '[(,)]' '{printf("#%02x%02x%02x\n",$2,$3,$4)}')"
elif [[ "$DispSer" == "x11" ]]; then 
	color=$(gpick -pso --no-newline)
else
  return 
fi

image=/tmp/${color}.png

main() {
	if [[ "$color" ]]; then
		# generate preview
		convert -size 48x48 xc:"$color" ${image}
		# notify about it
		dunstify -u low --replace=69 -i ${image} "$color, copied to clipboard."
    # copy color code to clipboard
		echo $color | tr -d "\n" | xclip -selection clipboard
		exit 0
	fi
}

# Run the script
main
