#!/bin/bash
WALL_DIR=~/Pictures/wallpapers
IMG=$( find $WALL_DIR -type f -name '*.png' -print0| shuf -n1 -z )

pgrep i3lock || ffmpeg  -loglevel panic -f x11grab -video_size \
				$(xdpyinfo | grep dimensions | sed -r 's/^[^0-9]*([0-9]+x[0-9]+).*$/\1/') -y -i :0.0+,20 -i "$IMG" -filter_complex "boxblur=9,overlay=(main_w-overlay_w)/3:(main_h-overlay_h)/2" -vframes 1 "/tmp/newimg"

i3lock -i "$IMG" 
